# Generated by Django 5.1.5 on 2025-01-21 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExamManualApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
