# Generated by Django 5.1.5 on 2025-01-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamManualApp', '0004_user_is_active_user_is_staff_user_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='BirthDay',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AlterField(
            model_name='user',
            name='FirstAuth',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Gender',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='PhoneNumber',
            field=models.CharField(default='none', max_length=15),
        ),
    ]
