# Generated by Django 5.1.5 on 2025-01-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamManualApp', '0005_alter_user_birthday_alter_user_firstauth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='FirstAuth',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Role',
            field=models.IntegerField(max_length=1),
        ),
    ]
