# Generated by Django 5.1.5 on 2025-01-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamManualApp', '0008_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Gender',
            field=models.CharField(default=5, max_length=1),
        ),
    ]
