# Generated by Django 5.1.5 on 2025-01-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamManualApp', '0009_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Role',
            field=models.IntegerField(default=2),
        ),
    ]
