# Generated by Django 5.1.5 on 2025-01-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamManualApp', '0010_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='user',
            name='FirstName',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='user',
            name='SurName',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Addres',
            field=models.TextField(verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='user',
            name='BirthDay',
            field=models.DateField(default='2000-01-01', verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Block',
            field=models.BooleanField(default=False, verbose_name='Заблокирован'),
        ),
        migrations.AlterField(
            model_name='user',
            name='FirstAuth',
            field=models.BooleanField(default=True, verbose_name='Первичная авторизация'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Gender',
            field=models.CharField(default=5, max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Login',
            field=models.CharField(max_length=255, unique=True, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='user',
            name='NumberPassport',
            field=models.CharField(max_length=20, verbose_name='Номер паспорта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Patronymic',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='user',
            name='PhoneNumber',
            field=models.CharField(default='none', max_length=15, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Role',
            field=models.IntegerField(default=2, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='SerialPassport',
            field=models.CharField(max_length=20, verbose_name='Серия паспорта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активный акк'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Персонал'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='СуперПользователь'),
        ),
    ]
