# Generated by Django 5.1.5 on 2025-01-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamManualApp', '0012_gender_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Gender',
            field=models.CharField(default=1, max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Role',
            field=models.IntegerField(default=1, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='Пароль'),
        ),
    ]
