# Generated by Django 5.1.5 on 2025-01-27 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExamManualApp', '0013_alter_user_gender_alter_user_role_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gender',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
