# Generated by Django 5.1.5 on 2025-01-29 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamManualApp', '0014_delete_gender_delete_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Пол')),
            ],
            options={
                'verbose_name': 'Пол',
                'verbose_name_plural': 'Гендеры',
                'db_table': 'Gender',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
                'db_table': 'Role',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='Gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ExamManualApp.gender', verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ExamManualApp.role', verbose_name='Роль'),
        ),
    ]
